# Generated by Django 5.1.6 on 2025-04-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0016_prediction_diabetes_pedigree"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="retype_password",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="temporary_password",
                help_text="Hashed password for the user",
                max_length=120,
            ),
            preserve_default=False,
        ),
    ]
